server:
  port: 80
logging:
  level:
    root: error
spring:
  web:
    resources:
      static-locations: classpath:/templates/
  main:
      banner-mode: off # 关闭打印标志

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_news?serverTimezone=UTC
    username: root
    password: dillonl0409.

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.java_ssm.mybatis.entity




